### ISSUE TITLE
Is typedef a type or a newtype or?

### ISSUE THREAD

**Issue by phadej** [well-typed/hs-bindgen#173]
Should we translate `typedef`s as `newtype`s or `type`s?

E.g.

```c
typedef struct foo_s { ... } foo_t;
```

as

```haskell
data Foo_s = ...
type Foo_t = Foo_s
```

or

```haskell
data Foo_s = ...
newtype Foo_t = MkFooT Foo_s
```

or should this be (eventually configuble?)

---

What about anonymous structs and enums?

```c
typedef struct { ... } foo_t;
```

currently we combine:

```haskell
data Foo_t = ...
```

or should we still use `type`/`newtype` over a representation of anonymous structs/enums/unions?

**Comment by edsko** [comment]
As regards the first point, I think they should probably be `newtype`s, so that they can be given different class instances; see also discussion at https://github.com/well-typed/hs-bindgen/issues/168#issuecomment-2365065773 .

**Comment by TravisCardwell** [comment]
I read the linked discussion and now better understand the decision to use `newtype` wrappers instead of `type` aliases.  My thoughts:

* A Haskell `type` alias provides the same level of semantic information as a C `typedef`.  The name serves as documentation, but the type is interchangeable with the aliased type.
* Creating different instances necessitates use of `newtype` wrappers, but I wonder if we will *generate* such instances?  Developers who use the generated types are free to create their own `newtype` wrappers as necessary.
* Even if we want to generate custom instances for specific types, we could generate `type` aliases for C `typedef`s and *additionally* generate `newtype` wrappers for those custom instances.

The concrete `Floating` `Double` example is an interesting one.  To ensure that the Haskell type behaves exactly the same as in C, an instance could be defined that uses `unsafeDupablePerformIO` and FFI to perform the operations in C.  I imagine, however, that this is something that users would do themselves, not something that we would generate.

If we translate `typedef double foo` as `newtype CFoo = CFoo` [`CDouble`][], which instances should we derive?  If we derive only `Storable`, then users are able to define their own instances, but they must derive various (orphan) instances or the type is difficult to use.  If we derive instances in the generated code, then users have to create their own `newtype` wrapper anyway if they need a different implementation.

[`CDouble`]: <https://hackage.haskell.org/package/base-4.20.0.1/docs/Foreign-C-Types.html#t:CDouble>

I am currently approaching this issue from the perspective of `struct` aliases.  To serve as a concrete example, consider `typedef struct foo {...} bar`.  A field defined as `struct foo x` can be assigned a value with a type declared as `struct foo` or `bar`.  A function declared as `void baz(bar *)` can be passed (a pointer to) a value with a type declared as `struct foo` or `bar`.

By using `newtype` wrappers to make these types distinct, we cannot do the same in the Haskell translation.  We must unwrap a `CBar` to store it in that field, and we must wrap a `CFoo` to pass it to that function.  This could get pretty annoying if the C API does not have consistent usage of type names.  (Hopefully most codebases have consistent usage.)

I think that most people define a `typedef` alias for all structures and consistently use that alias (aside from within the structure itself, where the `struct` tag is required).  This translates to Haskell code that uses the `newtype` wrappers everywhere, and accessing/updating fields requires unwrapping/re-wrapping.

I am of course happy to continue with the `newtype` wrappers if that is what we decide to do, but my intuition says that using `type` aliases would result in a translated API that is easier to use and better matches the C API.
