### ISSUE TITLE
Define list of "reserved" Haskell identifiers

### ISSUE THREAD

**Issue by edsko** [well-typed/hs-bindgen#258]
This avoids overly many qualified names in the generated code. Currently we are reserving `pure` and `return` (these could conceivably clash with C global variables or C functions). We'll also want to reserve names such as `CInt` (a type called `Int` in a C header would become `CInt` with the default name mangler, which would be incredibly confusing, and so we should treat that as a reserved keyboard); note that `Int` does not need to be reserved as the default name mangler will never generate it.

If people use a different name mangler, it is their responsibility to think about such issues (we should provide some guidance on what to think about).

**Comment by TravisCardwell** [comment]
I moved reserved names to a separate section, with documentation.

> This module defines various sets of reserved names that are used by the default name manglers.
>
> Users who create their own name manglers must consider the names that may be created.  For example, the default name manglers prefix types with `C`, so name `CInt` is reserved to avoid confusion if C code defines an `Int` type, while name `Int` does not need to be reserved because the default name manglers will never create that name.  These sets are exported for convenience, but it is the responsibility of users who create their own name manglers to reserve names to work with the implementation of their name manglers.

The reserved names are split into the following sets:

* Haskell keywords
* GHC extension keywords
* Names in the type namespace that `hs-bindgen` may use unqualified (currently empty)
* Names in the variable namespace that `hs-bindgen` may use unqualified
* Names in the type namespace that are reserved because using them could cause confusion
* Names in the variable namespace that are reserved because using them could cause confusion (currently empty)

Notes:

* I changed the keyword references to reference the GHC source (lexer).
* I refactored the `handleReservedNames` function to use `Set`.  The name mangler is used very often, so I would be surprised if the cost of constructing the set outweighs the cost of many linear scans of lists that could have many items.
